version: "3"

services:
    database:
        container_name: database
        image: percona:5.7
        volumes:
            - ${PWD}/data/db:/var/lib/db
        environment:
            - MYSQL_DATABASE=connect
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        networks:
            - symfony-network

    php-fpm:
        container_name: php-fpm
        depends_on:
            - connect-db
        volumes:
            - ${PWD}/../:/var/www
        environment:
            - ENV=${ENV}
            - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
            - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
        build:
            context: .
            dockerfile: ${PWD}/php-fpm/Dockerfile
        networks:
            - symfony-network

    nginx:
        container_name: nginx
        image: nginx:latest
        depends_on:
            - php-fpm
        ports:
            - 8000:80
        volumes:
            - ${PWD}/../:/var/www
            - ${PWD}/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony-network

networks:
    symfony-network: